application: flag-42
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: front/index.html
  upload: front/(.*\.html)

- url: /css
  static_dir: front/css

- url: /js
  static_dir: front/js

- url: /.*
  script: _go_app

