application: flag-42
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: app/index.html
  upload: app/(.*\.html)

- url: /js
  static_dir: app/js

- url: /css
  static_dir: app/css

- url: /lib
  static_dir: app/lib

- url: /img
  static_dir: app/img

- url: /partials
  static_dir: app/partials

- url: /.*
  script: _go_app
